<?php

namespace Yapeal\Entity\Fetcher;

use Doctrine\ORM\EntityRepository;

/**
 * CachedUntilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CachedUntilRepository extends EntityRepository
{
}
